### ISSUE TITLE
Outdated icons?

### ISSUE THREAD

**Issue by rgbinnovation** [phucgaoxam/line_awesome_icons_flutter#5]
Hi, there seems to be a lot of icons added since you last updated. Any chance of an update?

**Comment by rgbinnovation** [comment]
Let me know if you do, as your package is useless to me at the moment due to all of the missing icons. Hope Ill be able to use it soon!

**Comment by mateotomas2** [comment]
I also faced this problem. So I updated this library to use the latest version of line awesome.

If you want to try it you can add this in your pubspec.yaml:
```
line_awesome_icons: 
    git:
      url: git://github.com/mateotomasgomez/line_awesome_icons_flutter.git
      ref: master
```
